# CodeDeploy 버전. 프로젝트 버전이 아니므로, 0.0외에 다른 버전 사용 시 오류발생 -> 지금은 다를지도
version: 0.0
os: linux
files:
  - source: / # CodeDeploy에서 전달해 준 파일 중 destination 으로 이동시킬 대상 지정. 여기서는 / 로 root 지정. 즉 전체 파일을 이야기한다.
    destination: /home/ec2-user/app/step3/zip # source에서 지정한 파일을 받을 위치. 이후 Jar 실행 등은 여기에서 옮겨 사용한다.
    overwrite: yes

# CodeDeploy에서 EC2로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 함
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 단계레서 실행할 명령어 지정
# step2 버전
# hooks:
#   ApplicationStart: # ApplicationStart 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 함.
#     - location: deploy.sh
#       timeout: 60 # 스크립트가 60초 이상 실행될 시 실패
#       runas: ec2-user
# step3 버전
hooks:
  AfterInstall:
    - location: stop.sh # Nginx와 연결되지 않은 Boot 종료
      timout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # Nginx와 연결되지 않은 Port로 새 버전의 Boot 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 Boot 가 정상실행됬는지 확인
      timeout: 60
      runas: ec2-user
# Jar 파일이 복사된 후로 차례로 앞선 스크립트들이 실행된다고 보면 된다.